description: |  # Descriptive text to show when creating a project from this boilerplate
  ______       ___________            
  ___  /__________(_)__  /____________
  __  __ \  __ \_  /__  /_  _ \_  ___/
  _  /_/ / /_/ /  / _  / /  __/  /    
  /_.___/\____//_/  /_/  \___//_/.
  Test boilerplate for boiler cli app

vars: # Variables to be used in boiler files templates
  - {name: author , default: No author, question: Ask something about author}
  - {name: description, default: Awesome app, question: Ask something about description}

generators: # Generator after the boilerplate project is created, these are used to create units
  gofile:
    aliases: [.go]
    description: Creates a go file based on template                   # Description for --help
    files:                                                             # Files or folders to be processed, these files are relative to $PROJROOT/.boiler/template/...
      - {source: gofile.go.boiler, target: "{{.curdir}}/{{.name}}"}    # Target is processed with template
    vars:                                                              # List of variables for unit creation
      - name: package                                                  # Var name {{.package}}
        default: "{{.projName}}"                                       # Default value 
        flag: "package, p"                                             # command flags to set this var
        question: package name of the new file                         # question to be shown on interactive input
        description: Package to place on package thing                 # description of the var '--help'
        
  puretxt:
    description: Clones pure.txt file
    aliases: [.txt]
    files:
      - {source: pure.txt, target: "{{.curdir}}/{{.name}}" }

  package:
    description: Creates a package for app
    files:
      - {source: controller/pkg.go.boiler, target: "{{.projRoot}}/{{.name}}/{{.name}}"}
      - {source: controller/pkg_test.go.boiler, target: "{{.projRoot}}/{{.name}}/{{.name}}_test"}
